import { NextResponse } from "next/server";
import { getPaymentTransactionDetails } from "@/features/payment/payment.service";

export async function GET(
  req: Request,
  context: { params: Promise<{ tran_id: string }> },
) {
  try {
    const { tran_id } = await context.params;
    const { searchParams } = new URL(req.url);
    const shouldDownload = searchParams.get("download") === "1";
    const shouldPrint = searchParams.get("print") === "1";

    const transaction = await getPaymentTransactionDetails(tran_id);
    if (!transaction) {
      return NextResponse.json(
        { error: "Transaction not found" },
        { status: 404 },
      );
    }

    const amount = Number(transaction?.payment?.amount || 0).toFixed(2);
    const currency = transaction?.payment?.currency || "BDT";
    const paidAtRaw =
      transaction?.payment?.completedAt ||
      transaction?.payment?.initiatedAt ||
      transaction?.updatedAt ||
      new Date().toISOString();
    const paidAt = new Date(paidAtRaw).toLocaleString();

    const html = `<!doctype html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Invoice ${tran_id}</title>
    <style>
      body { font-family: Arial, sans-serif; margin: 24px; color: #0f172a; }
      .container { max-width: 820px; margin: 0 auto; border: 1px solid #e2e8f0; border-radius: 12px; padding: 24px; }
      .head { display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px; }
      .muted { color: #475569; }
      table { width: 100%; border-collapse: collapse; margin-top: 16px; }
      td, th { border: 1px solid #e2e8f0; padding: 10px; text-align: left; }
      th { background: #f8fafc; }
      .total { margin-top: 16px; text-align: right; font-size: 18px; font-weight: 700; }
      @media print { .no-print { display: none; } body { margin: 0; } .container { border: none; } }
    </style>
  </head>
  <body>
    <div class="container">
      <div class="head">
        <div>
          <h1>Shifa Invoice</h1>
          <p class="muted">Transaction ID: ${tran_id}</p>
          <p class="muted">Date: ${paidAt}</p>
        </div>
        <div>
          <strong>Status:</strong> ${transaction?.paymentStatus || "N/A"}
        </div>
      </div>

      <table>
        <tr><th>Field</th><th>Value</th></tr>
        <tr><td>Appointment ID</td><td>${transaction?.appointmentId || transaction?.payment?.appointmentId || "N/A"}</td></tr>
        <tr><td>Doctor</td><td>${transaction?.doctor?.name || "N/A"}</td></tr>
        <tr><td>Specialization</td><td>${transaction?.doctor?.specialization || "N/A"}</td></tr>
        <tr><td>Patient</td><td>${transaction?.patient?.fullName || "N/A"}</td></tr>
        <tr><td>Patient Email</td><td>${transaction?.patient?.email || "N/A"}</td></tr>
        <tr><td>Gateway</td><td>${transaction?.payment?.gateway || "sslcommerz"}</td></tr>
      </table>

      <div class="total">Total Paid: ${currency} ${amount}</div>

      <p class="muted" style="margin-top: 24px;">This invoice is system generated by Shifa Telemedicine.</p>
      ${shouldPrint ? "<script>window.print();</script>" : ""}
    </div>
  </body>
</html>`;

    const headers: Record<string, string> = {
      "Content-Type": "text/html; charset=utf-8",
    };

    if (shouldDownload) {
      headers["Content-Disposition"] =
        `attachment; filename="invoice-${tran_id}.html"`;
    }

    return new NextResponse(html, {
      status: 200,
      headers,
    });
  } catch (error) {
    return NextResponse.json(
      { error: "Failed to generate invoice" },
      { status: 500 },
    );
  }
}
