import { authOptions } from "@/features/Auth/auth.config";
import { collections, dbConnect } from "@/lib/dbConnect";
import { sendEmail } from "@/lib/Email/sendEmail";
import { ObjectId } from "mongodb";
import { getServerSession } from "next-auth";

export async function POST(req) {
  try {
    const session = await getServerSession(authOptions);

    // Check if user logged in
    if (!session) {
      return Response.json(
        {
          success: false,
          message: "Please login first",
        },
        { status: 401 },
      );
    }

    const body = await req.json();

    const supportCollection = await dbConnect(collections.SUPPORT_TICKETS);

    // Generate Ticket ID
    const ticketId = `SHIFA-${Math.floor(100000 + Math.random() * 900000)}`;

    const ticket = {
      ticketId,
      userId: new ObjectId(session.user.id),
      name: body.name,
      email: body.email,
      role: body.role,
      subject: body.subject,
      message: body.message,
      priority: body.priority || "normal",

      status: "open",
      createdAt: new Date(),
    };

    await supportCollection.insertOne(ticket);

    // Send confirmation email to user
    await sendEmail({
      to: session.user.email,
      subject: `Support Ticket Received - ${ticketId}`,
      html: `
  <div style="font-family:Arial, sans-serif;max-width:600px;margin:auto;background:#ffffff;padding:20px;border:1px solid #eee;border-radius:8px">

    <div style="text-align:center;margin-bottom:24px">
  <img 
    src="https://i.ibb.co.com/zTfjnT8w/shifa-logo.png" 
    alt="Shifa Logo"
    style="height:48px;display:block;margin:auto"
  />

  <div style="font-size:24px;font-weight:700;color:#059669;margin-top:8px">
    Shifa
  </div>

  <div style="font-size:12px;color:#6b7280;margin-top:2px">
    Telemedicine Platform
  </div>
</div>

    <h2 style="color:#2563eb;text-align:center">
      Support Ticket Received
    </h2>

    <p>Hello ${session.user.name || "User"},</p>

    <p>
      We received your support request successfully.
    </p>

    <p>
      <strong>Ticket ID:</strong> ${ticketId}
    </p>

    <p>
      Our support team will review your request and contact you within 
      <strong>24 hours</strong>.
    </p>

    <hr style="margin:20px 0"/>

    <h3>Your Message</h3>

    <p><strong>Subject:</strong> ${body.subject}</p>

    <p>${body.message}</p>

    <br/>

    <p>
      If you have additional information, you can reply to this email.
    </p>

    <br/>

    <p style="color:#555">
      Best Regards,<br/>
      Shifa Support Team
    </p>

  </div>
  `,
    });
    // send admin email notification
    await sendEmail({
      to: process.env.EMAIL_USER,
      subject: `New Support Ticket - ${ticketId}`,
      html: `
  <div style="font-family:Arial, sans-serif;max-width:600px;margin:auto;background:#ffffff;padding:20px;border:1px solid #eee;border-radius:8px">

    <div style="text-align:center;margin-bottom:24px">
      <img 
        src="https://i.ibb.co.com/zTfjnT8w/shifa-logo.png" 
        alt="Shifa Logo"
        style="height:48px;display:block;margin:auto"
      />

      <div style="font-size:24px;font-weight:700;color:#059669;margin-top:8px">
        Shifa
      </div>

      <div style="font-size:12px;color:#6b7280;margin-top:2px">
        Telemedicine Platform
      </div>
    </div>

    <h2 style="color:#111827;margin-bottom:10px">
      New Support Ticket Received
    </h2>

    <p style="color:#374151">
      A new support ticket has been submitted through the Shifa platform.
    </p>

    <hr style="margin:20px 0"/>

    <p><strong>Ticket ID:</strong> ${ticketId}</p>
    <p><strong>User Name:</strong> ${session.user.name || "N/A"}</p>
    <p><strong>User Email:</strong> ${session.user.email}</p>
    <p><strong>User Role:</strong> ${body.role}</p>
    <p><strong>Priority:</strong> ${body.priority || "Normal"}</p>

    <hr style="margin:20px 0"/>

    <h3 style="margin-bottom:6px">Subject</h3>
    <p>${body.subject}</p>

    <h3 style="margin-top:16px;margin-bottom:6px">Message</h3>
    <p>${body.message}</p>

    <hr style="margin:20px 0"/>

    <p style="font-size:13px;color:#6b7280">
      This email was automatically generated by the Shifa Support System.
    </p>

  </div>
  `,
    });

    // Send response to frontend
    return Response.json({
      success: true,
      ticketId,
      message: `Request submitted. Your ticket is ${ticketId}. Our team will contact you within 24 hours.`,
    });
  } catch (error) {
    console.error(error);

    return Response.json(
      {
        success: false,
        message: "Something went wrong. Please try again.",
      },
      { status: 500 },
    );
  }
}
