// src/config/role-permissions.ts

import { PERMISSIONS, Permission } from "./permissions";

export type Role = "admin" | "doctor" | "patient" | "ambulance_provider";

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  admin: [
    PERMISSIONS.MANAGE_DOCTORS,
    PERMISSIONS.MANAGE_PATIENTS,
    PERMISSIONS.VIEW_ALL_APPOINTMENTS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.MANAGE_SYSTEM_SETTINGS,
    PERMISSIONS.MANAGE_AMBULANCE_OPERATIONS,
  ],

  doctor: [
    PERMISSIONS.VIEW_ASSIGNED_APPOINTMENTS,
    PERMISSIONS.VIEW_ASSIGNED_PATIENTS,
    PERMISSIONS.WRITE_MEDICAL_REPORT,
    PERMISSIONS.UPDATE_DOCTOR_PROFILE,
    PERMISSIONS.MANAGE_DOCTOR_SCHEDULE,
  ],

  patient: [
    PERMISSIONS.BOOK_APPOINTMENT,
    PERMISSIONS.VIEW_OWN_APPOINTMENTS,
    PERMISSIONS.VIEW_OWN_HISTORY,
    PERMISSIONS.UPDATE_PATIENT_PROFILE,
    PERMISSIONS.APPLY_AMBULANCE_PROVIDER,
    PERMISSIONS.BOOK_AMBULANCE,
  ],

  ambulance_provider: [
    PERMISSIONS.MANAGE_AMBULANCE_PROVIDER_PROFILE,
    PERMISSIONS.MANAGE_AMBULANCE_AVAILABILITY,
    PERMISSIONS.VIEW_ASSIGNED_AMBULANCE_BOOKINGS,
  ],
};
